### ISSUE TITLE
Dynamic Services?

### ISSUE THREAD

**Issue by philippeboyd** [stefanprodan/mongo-swarm#5]
Can it be possible to make it dynamic?
For example : 

```
.....
  data:
    image: mongo:3.4
    networks:
      - mongo
    volumes:
      - data:/data/db
    command: mongod --shardsvr --replSet datars --smallfiles --port 27017
    deploy:
      mode: replicated
      replicas: 3
      placement:
        constraints:
          - node.labels.mongo.role == data
```
